# Generated by Django 6.0 on 2026-02-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_userprofile_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MINT', 'Minted'), ('TRANSFER', 'Transferred'), ('RECEIVED', 'Received'), ('SOLD', 'Sold to Patient')], max_length=10),
        ),
    ]
